### ISSUE TITLE
False positives: unused and never modified variable

### ISSUE THREAD

**Issue by simonorono** [Hackerpilot/Dscanner#378] opened 2016-11-18 12:58 UTC
Found while using a Visual Studio Code extension:

![1bff940c-ad45-11e6-9531-be92afed3b5c](https://cloud.githubusercontent.com/assets/12176276/20430843/0bdbecce-ad6d-11e6-8aa2-301803245b82.png)

The code shown:

```d
import std.algorithm: partition3;
import std.stdio: readln, writeln;

private void quicksort(T)(T[] arr) {
	if (arr.length >= 2) {
		auto p = partition3(arr, arr[0]);
		p[0].quicksort;
		p[2].quicksort;
	}
}

void main() {
	auto arr = [10, 9, 8];
	arr.quicksort;
	arr.writeln;
	readln();
}
```

Using the command line:

~~~
[simon@NV55C source]$ dscanner app.d -S
app.d(13:7)[warn]: Variable arr is never modified and could have been declared const or immutable.
app.d(13:7)[warn]: Variable arr is never used.
~~~

**Comment by Hackerpilot** [comment] 2016-12-06 00:20
This is caused by the parser not being able to determine that `.quicksort` and `.writeln` are actually function calls. (I think this is another reason that making parenthesis optional was a mistake)

I'm closing this because it's a duplicate of https://github.com/Hackerpilot/Dscanner/issues/325

**Closed by Hackerpilot** 2016-12-06 00:20 UTC

**Comment by simonorono** [comment] 2016-12-06 00:46
What about the `app.d(13:7)[warn]: Variable arr is never used.`? I don't see it mentioned in #325

**Comment by Hackerpilot** [comment] 2017-01-03 22:26
The reason that the unused variable warning is there is this:

```d
import std.stdio;

struct A { int alpha; }
struct B { int bravo() { writeln("Doing things"); return 10; } }

void main()
{
    A a;
    a.alpha; // This does nothing and `a` is unused
    B b;
    b.bravo; // This does something and `b` is used
}
```

Because there are no parenthesis in the `bravo` function call D-Scanner doesn't know that `b` is used. It's the same problem.
